{
 "title": "DevOpsProdigy KubeGraf Deployment's Dashboard",
 "tags": [
  "kubernetes",
  "DevOpsProdigy",
  "deployment",
  "KubeGraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "devopsprodidy-kubegraf-datasource"
   },
   { "name": "prom_ds", "query": "prom" },
   { "name": "PromDs", "query": "prometheus" },
   { "name": "namespace", "query": "namespace deployment" },
   { "name": "deployment", "query": "deployment $namespace" },
   {
    "name": "pod",
    "query": "query_result(avg_over_time(kube_pod_info{namespace=\"$namespace\",pod=~\"$deployment-.*\"}[$__range]))"
   },
   {
    "name": "container",
    "query": "query_result(avg_over_time(kube_pod_container_info{namespace=\"$namespace\",pod=~\"$deployment-.*\",container!=\"\",container!=\"POD\"}[$__range]))"
   }
  ]
 },
 "panels": [
  { "title": "Application Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods' status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$deployment\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"$namespace\", deployment=\"$deployment\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Pods' status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$deployment\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"$namespace\", deployment=\"$deployment\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Containers' statuses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Ready [$deployment / {{pod}} / {{container}}]"
    },
    {
     "expr": "kube_pod_container_status_running{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Running [$deployment / {{pod}} / {{container}}]"
    },
    {
     "expr": "kube_pod_container_status_waiting{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Waiting [$deployment / {{pod}} / {{container}}]"
    },
    {
     "expr": "kube_pod_container_status_terminated{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Terminated [$deployment / {{pod}} / {{container}}]"
    }
   ]
  },
  {
   "title": "Containers' restarts total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Containers' restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Restarts [$deployment / {{pod}} / {{ container}} ]"
    }
   ]
  },
  { "title": "Application's Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\", container=~\"$container\"}) by (pod, container) or sum(label_replace(label_replace(container_memory_working_set_bytes{namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"\", container_name!=\"POD\", container_name=~\"$container\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\"), \"container\", \"$1\", \"container_name\", \"(.*)\")) by (pod, container)",
     "legendFormat": "Used: {{pod}} / {{container}}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by (pod, container)",
     "legendFormat": "Requested: {{pod}} / {{container}}"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by (pod, container)",
     "legendFormat": "Limited: {{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[2m])) by (pod, container) or sum(label_replace(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}[2m]),\"pod\",\"$1\",\"pod_name\",\"(.*)\"),\"container\",\"$1\",\"container_name\",\"(.*)\")) by (pod, container)",
     "legendFormat": "Used: {{pod}} / {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Requested: {{pod}} / {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Limited: {{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[2m]) or\nlabel_replace(irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=~\"$pod\"}[2m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")",
     "legendFormat": "trans: [{{pod}}]"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[2m]) or label_replace(irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=~\"$pod\"}[2m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")",
     "legendFormat": "recv:  [{{pod}}]"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\"}[5m]) or label_replace(label_replace(rate(container_fs_reads_total{namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"\", container_name!=\"POD\"}[5m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\"), \"container\", \"$1\", \"container_name\", \"(.*)\")",
     "legendFormat": "Reads {{ device }} [{{ pod }} / {{ container }}]"
    },
    {
     "expr": "rate(container_fs_writes_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\"}[5m]) or label_replace(label_replace(rate(container_fs_writes_total{namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"\", container_name!=\"POD\"}[5m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\"), \"container\", \"$1\", \"container_name\", \"(.*)\")",
     "legendFormat": "Writes {{ device }} [{{ pod }} / {{ container }}]"
    }
   ]
  }
 ]
}