{
 "title": "DevOpsProdigy KubeGraf Pod's Dashboard",
 "tags": [
  "kubernetes",
  "DevOpsProdigy",
  "pod",
  "KubeGraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "devopsprodidy-kubegraf-datasource"
   },
   { "name": "prom_ds", "query": "prom" },
   { "name": "PromDs", "query": "prometheus" },
   { "name": "namespace", "query": "namespace" },
   {
    "name": "pod",
    "query": "query_result(avg_over_time(kube_pod_info{namespace=\"$namespace\"}[$__range]))"
   },
   {
    "name": "containers",
    "query": "query_result(avg_over_time(kube_pod_container_info{namespace=\"$namespace\", pod=\"$pod\"}[$__range]))"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=\"$pod\", container!=\"\", container!=\"POD\", container=~\"$containers\"}) or sum(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"\", container_name!=\"POD\", container_name=~\"$containers\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=\"$pod\", container=~\"$containers\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\", container=~\"$containers\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\", container=~\"$containers\"}[2m])) by (pod) or sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"\", container_name!=\"POD\", container_name=~\"$containers\"}[2m])) by (pod_name)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$containers\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$containers\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Traffic transmit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[2m]) or irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=\"$pod\"}[2m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Traffic receive",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[2m]) or irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=\"$pod\"}[2m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Containers' statuses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$containers\"}",
     "legendFormat": "Ready [{{pod}} / {{container}}]"
    },
    {
     "expr": "kube_pod_container_status_running{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$containers\"}",
     "legendFormat": "Running [{{pod}} / {{container}}]"
    },
    {
     "expr": "kube_pod_container_status_waiting{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$containers\"}",
     "legendFormat": "Waiting [{{pod}} / {{container}}]"
    },
    {
     "expr": "kube_pod_container_status_terminated{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$containers\"}",
     "legendFormat": "Terminated [{{pod}} / {{container}}]"
    }
   ]
  },
  {
   "title": "Containers' restarts total",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=~\"$containers\", pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Containers' restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=~\"$containers\", pod=\"$pod\"}",
     "legendFormat": "Restarts [{{pod}} / {{ container}} ]"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\"}[5m]) or label_replace(label_replace(rate(container_fs_reads_total{namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"\", container_name!=\"POD\"}[5m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\"), \"container\", \"$1\", \"container_name\", \"(.*)\")",
     "legendFormat": "Reads {{ device }} [{{ pod }} / {{ container }}]"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_writes_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\"}[5m]) or label_replace(label_replace(rate(container_fs_writes_total{namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"\", container_name!=\"POD\"}[5m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\"), \"container\", \"$1\", \"container_name\", \"(.*)\")",
     "legendFormat": "Writes {{ device }} [{{ pod }} / {{ container }}]"
    }
   ]
  }
 ]
}