{
 "title": "DevOpsProdigy KubeGraf Statefulset's Dashboard",
 "tags": [
  "kubernetes",
  "DevOpsProdigy",
  "statefulset",
  "KubeGraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "devopsprodidy-kubegraf-datasource"
   },
   { "name": "prom_ds", "query": "prom" },
   { "name": "PromDs", "query": "prometheus" },
   { "name": "namespace", "query": "namespace" },
   { "name": "statefulset", "query": "statefulset $namespace" },
   {
    "name": "container",
    "query": "label_values(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=~\"$statefulset-.*\", container_name!=\"\", container_name!=\"POD\"}, container_name)"
   },
   {
    "name": "pod",
    "query": "label_values(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=~\"$statefulset-.*\", container_name!=\"\", container_name!=\"POD\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Application Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Statefulset status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"$statefulset\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_statefulset_status_replicas_current{namespace=\"$namespace\", statefulset=\"$statefulset\"}) - sum(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"$statefulset\"}) ",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Statefulset status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas{namespace=\"$namespace\", statefulset=\"$statefulset\"}",
     "legendFormat": "created"
    },
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"$statefulset\"}",
     "legendFormat": "ready"
    },
    {
     "expr": "kube_statefulset_status_replicas_current{namespace=\"$namespace\", statefulset=\"$statefulset\"}",
     "legendFormat": "current"
    },
    {
     "expr": "kube_statefulset_status_replicas_updated{namespace=\"$namespace\", statefulset=\"$statefulset\"}",
     "legendFormat": "updated"
    }
   ]
  },
  {
   "title": "Containers' statuses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Ready [$statefulset / {{pod}} / {{container}}]"
    },
    {
     "expr": "kube_pod_container_status_running{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Running [$statefulset / {{pod}} / {{container}}]"
    },
    {
     "expr": "kube_pod_container_status_waiting{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Waiting [$statefulset / {{pod}} / {{container}}]"
    },
    {
     "expr": "kube_pod_container_status_terminated{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Terminated [$statefulset / {{pod}} / {{container}}]"
    }
   ]
  },
  {
   "title": "Containers' restarts total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Containers' restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Restarts [$statefulset / {{pod}} / {{ container}} ]"
    }
   ]
  },
  { "title": "Application's Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"\", container_name!=\"POD\", container_name=~\"$container\"}) by (pod_name)",
     "legendFormat": "Used: {{pod_name}} / {{$container}}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{ namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by (pod)",
     "legendFormat": "Requested: {{pod}} / {{$container}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}[2m])) by (pod_name)",
     "legendFormat": "Used: {{pod_name}} / {{$container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"$pod\", container_name=~\"$container\"}) by (pod)",
     "legendFormat": "Requested: {{pod}} / {{$container}}"
    }
   ]
  },
  {
   "title": "Traffic transmit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{interface}} : [{{pod_name}}]"
    }
   ]
  },
  {
   "title": "Traffic receive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{interface}} : [{{pod_name}}]"
    }
   ]
  }
 ]
}