const ERROR = 3;
const WARNING = 2;
const TERMINATING = 1;
const SUCCESS = 0;

const COLOR_YELLOW = '#ffff0096';
const COLOR_RED = '#a52a2a';
const COLOR_GREEN = '#299c46';

const PODS_LIMIT = 10;

const TYPE_PROMETHEUS = "prometheus";

export { ERROR, WARNING, TERMINATING, SUCCESS, COLOR_YELLOW, COLOR_RED, COLOR_GREEN, PODS_LIMIT, TYPE_PROMETHEUS}
